### PR TITLE
serving admin interface from server

### PR DESCRIPTION
**Pull request by quinkennedy**
I made some minor changes, and tested on Node 5.7.0, I would appreciate it if someone else tested this with a client or two before we merge it into master.

### CODE REVIEW

**Comment by robotconscience** [comment]
Cool dude. I can test more later! Tried a few this AM and looked good.

**Comment by robotconscience** [comment]
Stress tested this / tried with all types, different port. I think the only thing that would be good to fix/change would be the admin automatically connecting to the port it's on–e.g. "localhost:9001" would auto connect to 9001. What do you think?

**Comment by quinkennedy** [comment]
could be nice.

**Comment by quinkennedy** [comment]
fixes #67

**Pull request merged**
